# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2017-2019 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

sudo: false

notifications:
  email: false

language: python

matrix:
  fast_finish: true

cache:
  - pip

python:
  - "2.7"
  - "3.5"
  - "3.6"

before_install:
  - "travis_retry pip install --upgrade pip"
  - "travis_retry pip install cookiecutter"
  - "travis_retry pip install Sphinx>=1.4.2 sphinx_rtd_theme>=0.1.7"

script:
  - "./run-tests.sh"
